services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - db
  php-fpm:
    image: php:8.3-fpm-alpine
    volumes:
      - ./:/var/www/html
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: app
      MARIADB_USER: app
      MARIADB_PASSWORD: app
